# Generated by Django 5.1 on 2024-09-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_apirequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='output',
            field=models.IntegerField(),
        ),
    ]
