# Generated by Django 5.1 on 2024-09-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_apirequest_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='output',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
